### ISSUE TITLE
README diagram image needs to use an absolute URL for Bonsai display

### ISSUE THREAD

**Issue by cwjohnston** [sensu/sensu-relay-handler#6]
The cool image in the readme isn't visible on Bonsai because the rendered URL is relative.

**Comment by nixwiz** [comment]
This appears to be a Bonsai issue since the link in the README is absolute (Linking to the blame is the only way to link to line numbers in markdown files).

https://github.com/sensu/sensu-relay-handler/blame/master/README.md#L7

Bonsai page source:

```
<p><a href="images/relay_handler.png?raw=true%22Title%22" target="_blank"><img src="images/relay_handler.png?raw=true%22Title%22" alt="Relay Handler" style="max-width:100%;"></a></p>
```
